models/Profil.php
<?php

namespace app\models;

use Yii;
use yii2mod\user\models\UserModel as User;
use app\models\Lookup;
use app\models\JawabanSoal;
use app\models\Room;
use app\components\AmayaActiveRecord;

/**
 * This is the model class for table "m_profil".
 *
 * @property int $id
 * @property int $user_id
 * @property string $nama_lengkap
 * @property string $nomor_identitas
 * @property string $jenis_identitas
 * @property string $alamat_identitas
 * @property string $rt_identitas
 * @property string $rw_identitas
 * @property string $kelurahan_identitas
 * @property string $kecamatan_identitas
 * @property string $kota_identitas
 * @property string $provinsi_identitas
 * @property string $alamat_sekarang
 * @property string $rt_sekarang
 * @property string $rw_sekarang
 * @property string $kelurahan_sekarang
 * @property string $kecamatan_sekarang
 * @property string $kota_sekarang
 * @property string $provinsi_sekarang
 * @property string $tempat_lahir
 * @property string $tanggal_lahir
 * @property string $jenis_kelamin
 * @property string $status_perkawinan
 * @property string $no_telepon
 * @property string $no_handphone
 * @property string $ayah_kandung
 * @property string $ibu_kandung
 * @property string $email
 * @property string $keluarga_nama
 * @property string $keluarga_alamat
 * @property string $keluarga_no_telepon
 * @property string $kantor
 * @property string $kantor_cabang
 * @property string $nama_file
 * @property string $created_by
 * @property string $created_dt
 * @property string $updated_by
 * @property string $updated_dt
 * @property int $is_deleted
 * @property string $deleted_by
 * @property string $deleted_dt
 * @property string $manager_id
 */
class Profil extends AmayaActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'm_profil';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'nama_lengkap', 'alamat_sekarang', 'no_handphone'], 'required'],
            [['user_id', 'is_deleted'], 'integer'],
            [['alamat_identitas', 'alamat_sekarang', 'keluarga_alamat', 'nip'], 'string'],
            [
                [
                    'tanggal_lahir', 'created_dt', 'updated_dt', 'deleted_dt', 'manager_id', 'manager_id', 'nama_file', 
                    'posisi', 'request_to_recall', 'tanggal_berlaku', 'pendidikan_terakhir', 'agama',
                    'manager_room_id', 'no_telepon', 'umur'
                ], 'safe'],
            [['nama_lengkap', 'nomor_identitas', 'jenis_identitas', 'rt_identitas', 'rw_identitas', 'kelurahan_identitas', 'kecamatan_identitas', 'kota_identitas', 'provinsi_identitas', 'rt_sekarang', 'rw_sekarang', 'kelurahan_sekarang', 'kecamatan_sekarang', 'kota_sekarang', 'provinsi_sekarang', 'tempat_lahir', 'jenis_kelamin', 'status_perkawinan', 'no_telepon', 'no_handphone', 'ayah_kandung', 'ibu_kandung', 'email', 'keluarga_nama', 'keluarga_no_telepon', 'kantor', 'created_by', 'updated_by', 'deleted_by'], 'string', 'max' => 255],
        ];
    }

    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function getManager()
    {
        return $this->hasOne(self::className(), ['id' => 'manager_id']);
    }

    public function getLookupStatusProfil()
    {
        return $this->hasOne(Lookup::className(), ['id' => 'l_status_profil_id']);
    }

    public function getJawabanSoal()
    {
        return $this->hasMany(JawabanSoal::className(), ['id' => 'profil_id']);
    }

    public function getJawabanSoalSumberLowongan()
    {
        return $this->hasOne(JawabanSoal::className(), ['profil_id' => 'id'])->andOnCondition([
            'soal'=>'Dari mana anda mengetahui lowongan ini?']);
    }

    public function getManagerRoom()
    {
        return $this->hasOne(Room::className(), ['id' => 'manager_room_id']);
    }

    public function getFollowers()
    {
        return $this->hasMany(self::className(), ['id' => 'manager_id']);
    }
}

controllers/ProfilController.php
<?php

namespace app\controllers;

use Yii;
use Yii\helpers\ArrayHelper;
use app\components\AmayaController;
use app\components\AmayaHelpers;
use \app\models\Profil;
use \app\models\ProfilAwalForm;
use \app\models\SetManagerForm;
use \app\models\Lookup;
use \app\models\Room;
use \app\models\Kota;
use yii\web\Response;
use yii\helpers\Url;
use yii\web\UploadedFile;
use yii\helpers\FileHelper;

class ProfilController extends AmayaController
{
    public function actionCreate()
    {
        try 
        {
            $model = new ProfilAwalForm;

            $userRoleId = Yii::$app->user->identity->user_role_id;
            if ($userRoleId == 5) {
                $model->scenario = 'trainee';
            } elseif ($userRoleId == 3) {
                $model->scenario = 'manager';
            }
            $title = 'Tambah Profil';

            if (Yii::$app->request->isPost) {                
                $post = Yii::$app->request->post();
                $model->attributes = $post['ProfilAwalForm'];
                $model->nama_file_cv = UploadedFile::getInstance($model, 'nama_file_cv');
                $model->nama_file_ktp = UploadedFile::getInstance($model, 'nama_file_ktp');
                $model->nama_file_kk = UploadedFile::getInstance($model, 'nama_file_kk');
                $model->nama_file_ijazah = UploadedFile::getInstance($model, 'nama_file_ijazah');
                // $model->nama_file_skck = UploadedFile::getInstance($model, 'nama_file_skck');
                $model->nama_file_skck = "NULL";
                
                if ($model->posisi != 'Lainnya') {
                    // avoid validate
                    $model->posisi_lainnya = '-';
                }
                // var_dump($model);
                // die;
                if ($model->validate()) { 
                    // var_dump($model);
                    // die;
                    $profil = new Profil;
                    $profil->attributes = $model->attributes;
                    $profil->user_id = Yii::$app->user->id;
                    $profil->l_status_profil_id = 1;                    

                    if ($profil->posisi == 'Lainnya') {
                        $profil->posisi = $model->posisi_lainnya;
                    }

                    if ($profil->posisi == 'Lainnya') {
                        $profil->posisi = $model->posisi_lainnya;
                    }

                    $filenames = [];
                    // foreach ($profil->nama_file as $file) {
                    //     $filename = rand(100000, 999999) . '.' . $file->extension;
                    //     $file->saveAs('uploads/' . $filename);
                    //     $filenames[] = $filename;
                    // }
                    if ($userRoleId == 5) {
                        // var_dump($profil->nama_lengkap);
                        // $path = 'uploads/'. $profil->nama_lengkap;
                        // FileHelper::createDirectory($path);
                        // die;
                        $filenamecv = $model->nama_lengkap . '_cv.' . $model->nama_file_cv->extension;
                        $profil->nama_file = $model->nama_file_cv;
                        $profil->nama_file->saveAs('uploads/' . $filenamecv);
                        $filenames[] = $filenamecv;
                        $filenamektp = $model->nama_lengkap . '_ktp.' . $model->nama_file_ktp->extension;
                        $profil->nama_file = $model->nama_file_ktp;
                        $profil->nama_file->saveAs('uploads/' . $filenamektp);
                        $filenames[] = $filenamektp;
                        $filenamekk = $model->nama_lengkap . '_kk.' . $model->nama_file_kk->extension;
                        $profil->nama_file = $model->nama_file_kk;
                        $profil->nama_file->saveAs('uploads/' . $filenamekk);
                        $filenames[] = $filenamekk;
                        $filenameijazah = $model->nama_lengkap . '_ijazah.' . $model->nama_file_ijazah->extension;
                        $profil->nama_file = $model->nama_file_ijazah;
                        $profil->nama_file->saveAs('uploads/' . $filenameijazah);
                        $filenames[] = $filenameijazah;

                        // var_dump($profil->nama_lengkap);
                        // $path = 'uploads/'. $profil->nama_lengkap;
                        // FileHelper::createDirectory($path);
                        // // die;
                        // $filenamecv = $model->nama_lengkap . '_cv.' . $model->nama_file_cv->extension;
                        // $profil->nama_file = $model->nama_file_cv;
                        // $profil->nama_file->saveAs('uploads/' . $profil->nama_lengkap . '/' . $filenamecv);
                        // $filenames[] = $filenamecv;
                        // $filenamektp = $model->nama_lengkap . '_ktp.' . $model->nama_file_ktp->extension;
                        // $profil->nama_file = $model->nama_file_ktp;
                        // $profil->nama_file->saveAs('uploads/' . $profil->nama_lengkap . '/' . $filenamektp);
                        // $filenames[] = $filenamektp;
                        // $filenamekk = $model->nama_lengkap . '_kk.' . $model->nama_file_kk->extension;
                        // $profil->nama_file = $model->nama_file_kk;
                        // $profil->nama_file->saveAs('uploads/' . $profil->nama_lengkap . '/' . $filenamekk);
                        // $filenames[] = $filenamekk;
                        // $filenameijazah = $model->nama_lengkap . '_ijazah.' . $model->nama_file_ijazah->extension;
                        // $profil->nama_file = $model->nama_file_ijazah;
                        // $profil->nama_file->saveAs('uploads/' . $profil->nama_lengkap . '/' . $filenameijazah);

                        // $filenameskck = $model->nama_lengkap . '_skck.' . $model->nama_file_skck->extension;
                        // $profil->nama_file = $model->nama_file_skck;
                        // $profil->nama_file->saveAs('uploads/' . $filenameskck);
                        // $filenames[] = $filenameskck;
                    }

                    $profil->nama_file = implode(',', $filenames);

                    $profil->tanggal_lahir = date('Y-m-d', strtotime($profil->tanggal_lahir));

                    if ($profil->save()) {
                        Yii::$app->session->setFlash('success', "Profil tersimpan.");
                        return $this->redirect('index');
                    }else{
                        Yii::$app->session->setFlash('error', "Gagal Tersimpan.");
                    }
                }
                else{
                    // var_dump($model->validate());
                    // die;
                    Yii::$app->session->setFlash('error', "Isi Semua Kolom-kolom yang di ada di menu tambah Profil.");
                }
            }

            $lookupPosisi = Lookup::find()
                ->where(['type'=>'posisi'])
                ->asArray()->all();
            $rooms = Room::find()->asArray()->all();

            $listPosisi = ArrayHelper::map($lookupPosisi, 'name', 'name');
            $listPosisi['Lainnya'] = 'Lainnya';
            $listJenisKelamin = ['Laki-laki'=>'Laki-laki', 'Perempuan'=>'Perempuan'];
            $listRoom = ArrayHelper::map($rooms, 'id', 'nama_room');
            
            return $this->render('create', get_defined_vars());
        } 
        catch (ErrorException $e) 
        {
            Yii::$app->session->setFlash('error', $e->getMessage());
        }        
    }

    public function actionModalSetManager($id)
    {
        $model = new SetManagerForm;
        $model->id = $id;

        $managerList = Profil::find()
            ->joinWith('user')
            ->where(['user.user_role_id'=>3])
            ->asArray()
            ->all();

        if ($managerList) {
            $managerList = ArrayHelper::map($managerList, 'id', 'nama_lengkap');
        }

        return $this->renderAjax('_set_manager', get_defined_vars());
    }



    public function actionSetManager()
    {
        $post = Yii::$app->request->post();

        $model = new SetManagerForm;
        $model->load($post);
        if ($model->validate()) {
            $profil = Profil::findOne($model->id);
            $profil->manager_id = $model->manager_id;
            $profil->save();

            Yii::$app->session->setFlash('success', "Pilihan SBC telah tersimpan, Tunggu approve dari Team SBC untuk tahap selanjutnya.");
        }
    }

    public function actionIndex()
    {
        $title = 'Profil Pengguna';
        $profil = Profil::find()
            ->where(['user_id'=>Yii::$app->user->id])
            ->one();
        if (!$profil) {
            $username = Yii::$app->user->identity->username;
            Yii::$app->session->setFlash('danger', "User {$username} belum membuat profil sebelumnya. Silakan isi profil terlebih dahulu.");
            return $this->redirect('/profil/create');
        }

        $followers = $followerTrainees = $followerActives = $managers = $coWorkers = [];
        if ($profil->user->user_role_id == 3) { // manager
            $followers = Profil::find()
                ->joinWith('user')
                ->where([
                    // 'user.user_role_id'=>5,
                    'manager_id'=>$profil->id,
                    'manager_approved'=>1,
                    'm_profil.is_deleted'=>0,
                ])
                ->all();

            foreach ($followers as $key => $follower) {
                // var_dump($follower->user->user_role_id);
                if(($follower != null)&&($follower instanceof SysMessage)){
                    if ($follower->user->user_role_id == 5) {
                        $followerTrainees[] = $follower;
                    } elseif ($follower->user->user_role_id == 6) {
                        $followerActives[] = $follower;
                    }
                }

views/profil/_get_profil.php
<?php 

use yii\web\View; 
use yii\helpers\Html; 
?>
<style type="text/css">
    .dl-horizontal dt {
        text-align: left;
    }
</style>

<h3 style="margin-top: -10px;"><?= $model->nama_lengkap; ?><small> - <?= $model->user->userRole->name; ?> </small></h3>

<div class="box box-warning">
    <div class="box-header">
        
    </div>
    <div class="box-body">
        <div class="col-md-6">
            <table class="table table-responsive">
                <tbody>
                    <tr>
                        <th width="40%">Jenis Identitas</th>
                        <td><?= $model->jenis_identitas ? : '-'; ?></td>
                    </tr>
                    <tr>
                        <th>Nomor Identitas</th>
                        <td><?= $model->nomor_identitas ? : '-'; ?></td>
                    </tr>
                    <tr>
                        <th>Alamat</th>
                        <td><?= $model->alamat_identitas ? : '-'; ?></td>
                    </tr>
                    <tr>
                        <th>Alamat Sekarang</th>
                        <td><?= $model->alamat_sekarang ? : '-'; ?></td>
                    </tr>
                    <tr>
                        <th>Tempat, Tgl Lahir</th>
                        <td><?= ($model->tempat_lahir ? : '-') . ($model->tanggal_lahir ? ', ' . date('d M Y', strtotime($model->tanggal_lahir)) : ''); ?></td>
                    </tr>
                    <tr>
                        <th>Jenis Kelamin</th>
                        <td><?= $model->jenis_kelamin ? : '-'; ?></td>
                    </tr>
                    <tr>
                        <th>No. Telepon</th>
                        <td><?= $model->no_telepon ? : '-'; ?></td>
                    </tr>
                    <tr>
                        <th>No. Handphone</th>
                        <td><?= $model->no_handphone ? : '-'; ?></td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td><?= $model->email ? : '-'; ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <table class="table table-responsive">
                <tbody>
                    <tr>
                        <th width="40%">Status Perkawinan</th>
                        <td><?= $model->status_perkawinan ? : '-'; ?></td>
                    </tr>
                    <tr>
                        <th>Ayah Kandung</th>
                        <td><?= $model->ayah_kandung ? : '-'; ?></td>
                    </tr>
                    <tr>
                        <th>Ibu Kandung</th>
                        <td><?= $model->ibu_kandung ? : '-'; ?></td>
                    </tr>
                    <tr>
                        <th>Alamat Keluarga</th>
                        <td><?= $model->keluarga_alamat ? : '-'; ?></td>
                    </tr>
                    <tr>
                        <th>Nama Keluarga yang Bisa Dihubungi</th>
                        <td><?= $model->keluarga_nama ? : '-'; ?></td>
                    </tr>                    
                    <tr>
                        <th>No. Telepon Keluarga</th>
                        <td><?= $model->keluarga_no_telepon ? : '-'; ?></td>
                    </tr>
                    <tr>
                        <th></th>
                        <td></td>
                    </tr>
                    <tr>
                        <th></th>
                        <td></td>
                    </tr>
                    <tr>
                        <th>Posisi yang dilamar</th>
                        <td><?= $model->posisi ? : '-'; ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="box-footer">
        <?php if ($model->nama_file && $model->user->user_role_id == 4) : ?>
            <!-- <a type="button" href='profil/' class="btn btn-success btn-download-documents" data-id="<?= $model->id; ?>">Download Dokumen</button> -->
            <?php 
            echo Html::a('Download Dokumen', 'profil/download-dokumen?id=' . $model->id, ['class'=>'btn btn-success']);
            ?>
        <?php endif; ?>
    </div>
</div>

<?php 
$this->registerJs($this->render('js/get_profil.js'), View::POS_END);
?>

views/profil/_set_manager.php
<?php

use yii\helpers\Html;
use yii\web\View; 
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Profil */
/* @var $form ActiveForm */
?>

<!-- form start -->
<div class="profil-set-manager">
    <?php $form = ActiveForm::begin([
        'id' => 'set-manager-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
            'horizontalCssClasses' => [
                'label' => 'col-sm-4',
                // 'offset' => 'col-sm-offset-4',
                'wrapper' => 'col-md-7 col-sm-8',
                'error' => '',
                'hint' => '',
            ],
        ],
    ]); ?>
    <div class="box-body">
        <?= $form->field($model, 'manager_id')->dropDownList(
            $managerList,
            [
                'prompt'=>'--Pilih SBC--'
            ]
        ) ?>
        <?= $form->field($model, 'id')->hiddenInput(['value'=>$id])->label(false) ?>
    </div><!-- profil-create -->
    <div class="box-footer">
        <div class="col-md-7 col-sm-offset-4 col-sm-8">
            <?= Html::button('Simpan', ['class' => 'btn btn-primary btn-set-manager pull-right']) ?>
        <!-- </div> -->
    </div>
    <?php ActiveForm::end(); ?>
</div>


<?php 
$this->registerJs($this->render('js/set_manager.js'), View::POS_END);
?>

views/profil/index_manager.php
<?php
use yii\web\View; 
use yii\helpers\Html; 
$this->title = 'Profil Manager';
?>

<style type="text/css">
    .box.box-default {
        height: 280px;
    }
</style>

<div class="box-header with-border">
    <h3 class="box-title"><?= isset($title) ? $title : $this->title; ?></h3>
</div>

<div class="box-body">
    <div class="row">
        <div class="col-md-4">
            <!-- Widget: user widget style 1 -->
            <div class="box box-widget widget-user">
                <!-- Add the bg color to the header using any of the bg-* classes -->
                <div class="widget-user-header bg-aqua-active" style='background-color: #086311 !important'>
                    <h3 class="widget-user-username"><?= $profil->nama_lengkap; ?></h3>
                    <h5 class="widget-user-desc"><?= $profil->user->userRole->name; ?></h5><?= $profil->managerRoom ? $profil->managerRoom->nama_room : '-';?>
                </div>
                <div class="widget-user-image">
                    <img class="img-circle" src="/img/profile/default.jpg" alt="User Avatar">
                </div>
                <br>
                <div class="box-footer">
                    <div class="row">
                        <div class="col-sm-4 border-right">
                            <div class="description-block">
                                <h5 class="description-header"><?= ($followerActives ? count($followerActives) : 0) + ($followerTrainees ? count($followerTrainees) : 0); ?></h5>
                                <span class="description-text">Total Tim</span>
                            </div>
                        </div>
                        <div class="col-sm-4 border-right">
                            <div class="description-block">
                                <h5 class="description-header"><?= $followerTrainees ? count($followerTrainees) : 0; ?></h5>
                                <span class="description-text">Trainee</span>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="description-block">
                                <h5 class="description-header"><?= $followerActives ? count($followerActives) : 0; ?></h5>
                                <span class="description-text">MT / BC</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.widget-user -->
        </div>
    </div>

    <!-- follower trainee -->
    <h3 class="box-title">Anggota Tim</h3>
    <?php if ($followerTrainees) : ?>
        <div class="row">
            <?php foreach ($followerTrainees as $followerTrainee) : ?>
            <div class="col-md-3">
                <!-- Profile Image -->
                <div class="box box-default">
                    <div class="box-body box-profile">
                        <img class="profile-user-img img-responsive img-circle" src="/img/profile/default.jpg" alt="User profile picture">
                        <h3 class="profile-username text-center"><?= $followerTrainee->nama_lengkap; ?></h3>
                        <p class="text-muted text-center"><?= $followerTrainee->user->userRole->name; ?></p>

                        <?php if ($followerTrainee->user->user_role_id == 3) : ?> <!-- manager -->
                            <ul class="list-group list-group-unbordered">
                                <li class="list-group-item">
                                    <b>Total Anggota Tim</b> <a class="pull-right">1,322</a>
                                </li>
                                <li class="list-group-item">
                                    <b>Jumlah Trainer</b> <a class="pull-right">543</a>
                                </li>
                                <li class="list-group-item">
                                    <b>Jumlah Tim Masuk</b> <a class="pull-right">13,287</a>
                                </li>
                            </ul>
                        <?php elseif ($followerTrainee->user->user_role_id == 5) : ?>
                            <div class="text-center">
                                <?php 
                                if ($followerTrainee) {
                                    if ($followerTrainee->manager_approved == 1)  {
                                        echo '<i class="fa fa-star"></i> ';
                                    } else {
                                        echo '<i class="fa fa-star-o"></i> ';
                                    }

                                    if ($followerTrainee->has_soal_submitted == 1) {
                                        if ($followerTrainee->has_soal_approved == 1) { // berhasil lolos soal
                                            echo '<i class="fa fa-star"></i> ';
                                        } else if ($followerTrainee->has_soal_approved == 2) { // gagal lolos Soal
                                            if ($followerTrainee->response_recall != 1) {
                                                echo '<i class="fa fa-star-half-o"></i> ';
                                            } else {
                                                echo '<i class="fa fa-star"></i> ';
                                            }
                                        } else {
                                            echo '<i class="fa fa-star-o"></i> ';
                                        }
                                    } else {
                                        echo '<i class="fa fa-star-o"></i> ';
                                    }

                                } else {
                                    echo '<i class="fa fa-star-o"></i> ';
                                    echo '<i class="fa fa-star-o"></i> ';
                                } 
                                ?>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                            </div>
                        <?php endif; ?>

                        <button class="btn btn-primary btn-block btn-profile-detail" data-id="<?= $followerTrainee->id ?>">
                            <b>Lihat Detail</b>
                        </button>

                        <div id="request_to_recall-<?= $followerTrainee->id ?>">
                            <?php if ($followerTrainee->has_soal_approved == 2) : ?>
                                <?php if ($followerTrainee->request_to_recall == 0) : ?>
                                <button class="btn btn-warning btn-sm pull-right btn-request_recall" data-id="<?= $followerTrainee->id ?>" style="margin-top: 5px">Recall</button>
                                <?php else : ?>
                                    <?php if ($followerTrainee->response_recall == 0) : ?>
                                        <span class="pull-right badge bg-orange"  style="margin-top: 5px">On Progress Recall</span>
                                    <?php elseif ($followerTrainee->response_recall == 1) : ?>
                                        <span class="pull-right badge bg-green"  style="margin-top: 5px">Recall Success</span>
                                    <?php endif; ?>
                                <?php endif; ?>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>



    <!-- MT / BC -->
    <h3 class="box-title">MT / BC</h3>
    <?php if ($followerActives) : ?>
        <div class="row">
            <?php foreach ($followerActives as $followerActive) : ?>
            <div class="col-md-3">
                <!-- Profile Image -->
                <div class="box box-default">
                    <div class="box-body box-profile">
                        <img class="profile-user-img img-responsive img-circle" src="/img/profile/default.jpg" alt="User profile picture">
                        <h3 class="profile-username text-center"><?= $followerActive->nama_lengkap; ?></h3>
                        <p class="text-muted text-center"><?= $followerActive->user->userRole->name; ?></p>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>


<div class="modal fade" id="modal-profile">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body" id="modal-profile-content">
                
            </div>
        </div>
    <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<?php
$this->registerJs($this->render('js/index.js'), View::POS_END);
?>