controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Profil;
use yii2mod\user\models\UserModel;
use yii2mod\user\actions\Action;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'login' => [
                'class' => 'yii2mod\user\actions\LoginAction'
            ],
            'logout' => [
                'class' => 'yii2mod\user\actions\LogoutAction'
            ],
            'signup' => [
                'class' => 'yii2mod\user\actions\SignupAction'
            ],
            'request-password-reset' => [
                'class' => 'yii2mod\user\actions\RequestPasswordResetAction'
            ],
            'password-reset' => [
                'class' => 'yii2mod\user\actions\PasswordResetAction'
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        if (Yii::$app->user->isGuest) {
            $model = new LoginForm();
            return $this->redirect('/site/front');
        }

        $profil = Profil::find()
            ->where(['user_id'=>Yii::$app->user->id])
            ->one();
        if (!$profil) {
            return $this->redirect('/profil/create');
        }
        
        $role_id = Yii::$app->user->identity->user_role_id;
        if ($role_id == 4) { // HRD
            return $this->redirect('/dashboard/index');
        }

        return $this->render('index');
    }

    public function actionFront()
    {
        $this->layout = '@app/views/adminLTE/layouts/main-front';
        return $this->render('front');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        // echo(123);
        // die;
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    /**
     * Displays about page.
     *
     * @return string
     */
    public function action403()
    {
        return $this->render('403');
    }


    public function actionActivate($token)
    {
        $user = UserModel::find()
            ->andWhere(['password_reset_token' => $token])
            ->one();
        if ($user) {
            $user->status = 1;
            $user->removePasswordResetToken();

            // if (Yii::$app->getUser()->login($user)) {
            if ($user->save()) {
                Yii::$app->getSession()->setFlash('success', 'Akun berhasil diaktifkan. Silakan login kembali.');
                // return $this->redirect(Yii::$app->getUser()->getReturnUrl());
            } else {
                Yii::$app->getSession()->setFlash('error', 'Akun gagal diaktifkan');
            }
            return $this->redirect('/site/login');
        } else {
            Yii::$app->getSession()->setFlash('error', 'Token expired.');
            return $this->redirect('/site/login');
        }
    }

    public function actionSistemPenerimaanKaryawan()
    {
        return $this->render('spk');
    }

    public function actionProduk()
    {
        return $this->render('produk');
    }

    public function actionLegalitas()
    {
        return $this->render('legalitas');
    }

    public function actionKegiatanKami()
    {
        return $this->render('kegiatan-kami');
    }
}

views/adminLTE/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use dmstr\widgets\Alert;

?>
<div class="content-wrapper">
    <section class="content-header">
        <!-- <?php if (isset($this->blocks['content-header'])) { ?>
            <h1><?= $this->blocks['content-header'] ?></h1>
        <?php } else { ?>
            <h1>
                <?php
                if ($this->title !== null) {
                    echo \yii\helpers\Html::encode($this->title);
                } else {
                    echo \yii\helpers\Inflector::camel2words(
                        \yii\helpers\Inflector::id2camel($this->context->module->id)
                    );
                    echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
                } 
                ?>
            </h1>
        <?php } ?> -->

        <?=
        Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        ) ?>
    </section>

    <section class="content">
        <div class="box box-success">

            <?= Alert::widget() ?>
            <?= $content ?>

        </div>
    </section>
</div>

<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> BETA
    </div>
    <strong>Copyright &copy; 2019 <a href="http://rf-berjangka.com">Rifan Financindo Berjangka Bandung</a></strong>
</footer>

<!-- <aside class="control-sidebar control-sidebar-dark">
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>

    <div class="tab-content">
    
        <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class='control-sidebar-menu'>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-user bg-yellow"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                            <p>New phone +1(800)555-1234</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                            <p>nora@example.com</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-file-code-o bg-green"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                            <p>Execution time 5 seconds</p>
                        </div>
                    </a>
                </li>
            </ul>

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class='control-sidebar-menu'>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="label label-danger pull-right">70%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Update Resume
                            <span class="label label-success pull-right">95%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Laravel Integration
                            <span class="label label-waring pull-right">50%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Back End Framework
                            <span class="label label-primary pull-right">68%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                        </div>
                    </a>
                </li>
            </ul>
        </div>


        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Some information about this general settings option
                    </p>
                </div>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Allow mail redirect
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Other sets of options are available
                    </p>
                </div>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Expose author name in posts
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Allow the user to show his name in blog posts
                    </p>
                </div>

                <h3 class="control-sidebar-heading">Chat Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Show me as online
                        <input type="checkbox" class="pull-right" checked/>
                    </label>
                </div>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Turn off notifications
                        <input type="checkbox" class="pull-right"/>
                    </label>
                </div>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Delete chat history
                        <a href="javascript::;" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                    </label>
                </div>
            </form>
        </div>
    </div>
</aside> -->
<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->
<div class='control-sidebar-bg'></div>

views/adminLTE/layouts/left.php
<?php 
use yii\helpers\Html;
use yii\helpers\Url;
 ?>
<style type="text/css">
     .main-sidebar {
        background-color: #00441a !important; 
     }
</style>

<aside class="main-sidebar">

    <section class="sidebar">

        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="/img/profile/default.jpg" class="img-circle" alt="User Image"/>
            </div>
            <div class="pull-left info">
                <p><?php echo Yii::$app->user->identity->username; ?></p>

                <!-- <a href="#"><i class="fa fa-circle text-success"></i> Trainee</a> -->
                <div>
                    <?php if (Yii::$app->user->identity->user_role_id == 5) : ?>
                        <?php
                        $profil = new app\models\Profil;
                        $profil = $profil->find()
                            ->where(['user_id'=> Yii::$app->user->id])
                            ->one();
                        ?>
                        <?php
                        if ($profil) {
                            if ($profil->manager_approved == 1)  {
                                echo '<i class="fa fa-star"></i> ';
                                // echo '<i class="fa fa-star" data-toggle="tooltip" data-placement="bottom" title="Popover title" data-content="Right?"></i> ';
                            } else {
                                echo '<i class="fa fa-star-o"></i> ';
                            }

                            if ($profil->has_soal_submitted == 1) {
                                if ($profil->has_soal_approved == 1) {
                                    echo '<i class="fa fa-star"></i> ';
                                } elseif ($profil->has_soal_approved == 2) { // gagal di sesi soal
                                    if ($profil->response_recall != 1) {
                                        echo '<i class="fa fa-star-half-o"></i> ';
                                    } else {
                                        echo '<i class="fa fa-star"></i> ';
                                    }
                                } else {
                                    echo '<i class="fa fa-star-o"></i> ';
                                }
                            } else {
                                echo '<i class="fa fa-star-o"></i> ';
                            }

                            if ($profil->tanggal_finger) {
                                echo '<i class="fa fa-star"></i> ';
                            } else {
                                echo '<i class="fa fa-star-o"></i> ';
                            }

                            if ($profil->drop_manager) {
                                echo '<i class="fa fa-star"></i> ';
                            } else {
                                echo '<i class="fa fa-star-o"></i> ';
                            }

                        } else {
                            echo '<i class="fa fa-star-o"></i> ';
                            echo '<i class="fa fa-star-o"></i> ';
                            echo '<i class="fa fa-star-o"></i> ';
                            echo '<i class="fa fa-star-o"></i> ';
                        }
                        ?>
                    <?php else : ?>
                        <?php echo Yii::$app->user->identity->userRole->name; ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>

        <!-- search form -->
        <!-- <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
              <span class="input-group-btn">
                <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
            </div>
        </form> -->
        <!-- /.search form -->

        <?= dmstr\widgets\Menu::widget(
            [
                'options' => ['class' => 'sidebar-menu tree', 'data-widget'=> 'tree'],
                'items' => [
                    // ['label' => 'Menu Yii2', 'options' => ['class' => 'header']],
                    // ['label' => 'Home', 'icon' => 'home', 'url' => ['/'], 'visible'=>in_array(Yii::$app->user->identity->user_role_id, [4]) ? false : true],
                    ['label' => 'Home', 'icon' => 'home', 'visible'=>in_array(Yii::$app->user->identity->user_role_id, [4]) ? false : true, 'items'=>[
                        ['label' => 'Tentang Kami', 'icon' => '', 'url' => ['/'], 'visible'=>in_array(Yii::$app->user->identity->user_role_id, [3]) ? true : false],
                        ['label' => 'Tentang RFB Bandung', 'icon' => '', 'url' => ['/about-rfb']],
                        ['label' => 'Tentang Tim Jojo', 'icon' => '', 'url' => ['/about-jojo-team']],
                        ['label' => 'Penerimaan Karyawan', 'icon' => '', 'url' => ['/site/sistem-penerimaan-karyawan']],
                        ['label' => 'Produk', 'icon' => '', 'url' => ['/site/produk']],
                        ['label' => 'Legalitas', 'icon' => '', 'url' => ['/site/legalitas']],
                        ['label' => 'Info & Kegiatan Kami', 'icon' => '', 'url' => ['/site/kegiatan-kami']],
                    ]],
                    ['label' => 'Dashboard', 'icon' => 'dashboard', 'url' => ['/dashboard'], 'visible'=>in_array(Yii::$app->user->identity->user_role_id, [4]) ? true : false],
                    ['label' => in_array(Yii::$app->user->identity->user_role_id, [5]) ? 'Profil' : 'Team', 'icon' => 'user', 'url' => ['/profil']],

                    ['label' => 'Info', 'icon' => 'dashboard', 'items' => [
                        ['label' => 'Trainee', 'icon' => '', 'url' => ['/info-trainee'], 'visible'=>in_array(Yii::$app->user->identity->user_role_id, [3, 4]) ? true : false],
                        ['label' => 'SBC & MT/BC', 'icon' => '', 'url' => ['/info-manager'], 'visible'=>in_array(Yii::$app->user->identity->user_role_id, [4]) ? true : false],
                        ['label' => 'Room', 'icon' => '', 'url' => ['/info-room'], 'visible'=>in_array(Yii::$app->user->identity->user_role_id, [4]) ? true : false],
                    ]],
                    // ['label' => 'Login', 'url' => ['site/login'], 'visible' => Yii::$app->user->isGuest],
                    // [
                    //     'label' => 'Some tools',
                    //     'icon' => 'share',
                    //     'url' => '#',
                    //     'items' => [
                    //         ['label' => 'Gii', 'icon' => 'file-code-o', 'url' => ['/gii'],],
                    //         ['label' => 'Debug', 'icon' => 'dashboard', 'url' => ['/debug'],],
                    //         [
                    //             'label' => 'Level One',
                    //             'icon' => 'circle-o',
                    //             'url' => '#',
                    //             'items' => [
                    //                 ['label' => 'Level Two', 'icon' => 'circle-o', 'url' => '#',],
                    //                 [
                    //                     'label' => 'Level Two',
                    //                     'icon' => 'circle-o',
                    //                     'url' => '#',
                    //                     'items' => [
                    //                         ['label' => 'Level Three', 'icon' => 'circle-o', 'url' => '#',],
                    //                         ['label' => 'Level Three', 'icon' => 'circle-o', 'url' => '#',],
                    //                     ],
                    //                 ],
                    //             ],
                    //         ],
                    //     ],
                    // ],
                ],
            ]
        ) ?>

    </section>

</aside>

views/adminLTE/layouts/main-front.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;
use dmstr\widgets\Alert;

/* @var $this \yii\web\View */
/* @var $content string */

dmstr\web\AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="front-page">

<?php $this->beginBody() ?>
    <?= Alert::widget() ?>
    <?= $content ?>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/adminLTE/layouts/main-login.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;
use dmstr\widgets\Alert;

/* @var $this \yii\web\View */
/* @var $content string */

dmstr\web\AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <style type="text/css">
        .login-page {
            width: 100%;
            height: 100vh;
            background-position: center center;
            background-size: cover;
            background-repeat: no-repeat;
            backface-visibility: hidden;
            animation: slideBg 60s linear infinite 0s;
            animation-timing-function: ease-in-out;
            background-image: url('/img/bg/1.jpg');
            color: white !important;
        }
        @keyframes slideBg {
            0% {
                background-image: url('/img/bg/1.jpg');
            }
            20% {
                background-image: url('/img/bg/2.jpg');
            }
            40% {
                background-image: url('/img/bg/3.jpg');
            }
            60% {
                background-image: url('/img/bg/4.jpg');
            }
            80% {
                background-image: url('/img/bg/5.jpg');
            }
            100% {
                background-image: url('/img/bg/6.jpg');
            }
        }

        .login-logo {
            color: #666666 !important;
        }
        .login-box-body {
            /*opacity: 0.5;*/
            background-color: rgba(255, 255, 255, 0.5);
        }

    </style>
</head>
<body class="login-page">

<?php $this->beginBody() ?>
    <div class="login-box">
        <?= Alert::widget() ?>
        <div class="login-logo">
            <b>PT. RFB</b> - Bandung
        </div>
        <!-- /.login-logo -->
        <div class="login-box-body">
            <?= $content ?>
        </div>
    </div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/adminLTE/layouts/main.php
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

if (Yii::$app->controller->action->id === 'login') { 
/**
 * Do not use this code in your template. Remove it. 
 * Instead, use the code  $this->layout = '//main-login'; in your controller.
 */
    echo $this->render(
        'main-login',
        ['content' => $content]
    );
} else {

    if (class_exists('backend\assets\AppAsset')) {
        backend\assets\AppAsset::register($this);
    } else {
        app\assets\AppAsset::register($this);
    }

    dmstr\web\AdminLteAsset::register($this);

    $directoryAsset = Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist');
    ?>
    <?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body class="hold-transition <?= \dmstr\helpers\AdminLteHelper::skinClass() ?> sidebar-mini">
    <?php $this->beginBody() ?>
    <div class="wrapper">

        <?= $this->render(
            'header.php',
            ['directoryAsset' => $directoryAsset]
        ) ?>

        <?php
        echo $this->render(
            'left.php',
            ['directoryAsset' => $directoryAsset]
        )
        ?>

        <?= $this->render(
            'content.php',
            ['content' => $content, 'directoryAsset' => $directoryAsset]
        ) ?>

    </div>

    <?php $this->endBody() ?>
    </body>
    </html>
    <?php $this->endPage() ?>
<?php } ?>