controllers/InfoTraineeController.php
<?php

namespace app\controllers;

use Yii;
use app\components\AmayaController;
use app\components\AmayaHelpers;
use \app\models\Profil;
use \app\models\JawabanSoal;
use yii\web\Response;
use yii\helpers\Html;
use yii\data\ArrayDataProvider;
use yii2mod\user\models\UserModel;

use PhpOffice\PhpSpreadsheet\Spreadsheet; 
use PhpOffice\PhpSpreadsheet\Writer\Xlsx; 

use yii\base\ErrorException;

class InfoTraineeController extends AmayaController {
    public $user;
    public function init() {
        if (Yii::$app->user->isGuest) return ;
        $this->user = Yii::$app->user->identity;
        if (!in_array($this->user->user_role_id, [3, 4])) {
            return $this->redirect('/site/403');
        }
    }

    public function actionIndex()
    {
        $title = 'Informasi Trainee';

        return $this->render('index', get_defined_vars());
    }

    public function actionGetData()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $request = Yii::$app->request;
        $is_manager = Yii::$app->user->identity->user_role_id == 3 ? true : false;


        $model = Profil::find()
            ->joinWith(['lookupStatusProfil', 'user'])
            ->where(['user_role_id'=>5, 'm_profil.is_deleted'=>0]);
        if ($is_manager) {
            $manager = Profil::find()
                ->where(['user_id'=>Yii::$app->user->id])
                ->one();
            $model->andWhere(['manager_id'=>$manager->id]);
        }
        $model = $model->orderBy(['id'=>SORT_DESC])
            ->asArray()->all();

        $data = [];
        foreach ($model as $key => $each) {// action button - start
            $aksi = [];
            if ($each['nama_file']) {
                $aksi[] = Html::a('Download Dokumen', '/profil/download-dokumen?id=' . $each['id'], ['class'=>'btn btn-success btn-xs']);
            }

            if ($each['l_status_profil_id'] == 1 && $is_manager == false) {
                $aksi[] = Html::button('Aktifkan', [
                    'class'=>'btn btn-xs btn-info btn-aktivasi',
                    'data-id'=>$each['id'],
                ]);
            } elseif ($each['l_status_profil_id'] == 2) {
                if ($each['manager_id']) {
                    if ($each['manager_approved'] == 0 && $is_manager == true) {
                        $aksi[] = Html::button('Approve SBC', [
                            'class'=>'btn btn-xs btn-info btn-approve-manager',
                            'data-id'=>$each['id'],
                            'data-managerId'=>$each['manager_id'],
                        ]);
                    } else {
                        if ($each['request_to_recall'] == 1 && $is_manager == false) {
                            if ($each['response_recall'] == 0) {
                                $aksi[] = Html::button('Approve Recall', [
                                    'class'=>'btn btn-xs btn-info btn-approve-recall',
                                    'data-id'=>$each['id'],
                                    'data-managerId'=>$each['manager_id'],
                                ]);
                            }
                        }

                        if ($each['tanggal_finger']) {
                            if (!$each['drop_manager']) {
                                $aksi[] = Html::button('Drop SBC', [
                                    'class'=>'btn btn-xs btn-info btn-drop-manager',
                                    'data-id'=>$each['id'],
                                    'data-managerId'=>$each['manager_id'],
                                ]);
                                $aksi[] = '<button type="button" class="btn btn-xs btn-info btn-drop-manager" data-id="'.$each['id'].'" data-managerId="'.$each['manager_id'].'">Drop SBC</button>';
                            } else {
                                if ($is_manager == false) {
                                    $aksi[] = Html::button('Lolos Trainee', [
                                        'class'=>'btn btn-xs btn-info btn-lolos-trainee',
                                        'data-id'=>$each['id'],
                                        'data-managerId'=>$each['manager_id'],
                                    ]);
                                } 
                            }
                        }
                    }
                }
            }

            $data[$key] = $each;

            $data[$key]['nama_lengkap'] = Html::button($each['nama_lengkap'], ['class'=>'btn btn-link btn-profile-detail', 'data-id'=>$each['id']]);
            $btn = implode('<br>', $aksi);
            // $btn = '<div id="content-"'. $each['id'] . '"></div>';
            $data[$key]['nama_lengkap'] .= "<i class='fa fa-info' data-toggle='popover' data-container='body' data-trigger='click' data-html=true data-placement='right' data-content='".$btn."'></i>";

            $manager = Profil::findOne($each['manager_id']);
            if ($manager) {
                $data[$key]['manager'] = $manager ? $manager->nama_lengkap : '';
                if ($manager->is_deleted == 1) {
                    $data[$key]['manager'] .= ' (DELETED)';
                }
                $data[$key]['room'] = $manager->managerRoom->nama_room;
            } else {
                $data[$key]['manager'] = '';
                $data[$key]['room'] = '';
            }

            $data[$key]['ttl'] = $each['tempat_lahir'] . ', ' . date('d M Y', strtotime($each['tanggal_lahir']));
            $data[$key]['umur'] = AmayaHelpers::getUmur($each['tanggal_lahir']);

            if ($each['l_status_profil_id'] == 1) {
                $statusName = $each['lookupStatusProfil']['name'];
                $badge = "bg-red";
                $message = $statusName; 
            } else {
                if ($each['manager_id']) {
                    if ($each['manager_approved'] == 0) {
                        $badge = "bg-orange";
                        $message = 'Request SBC';
                    } else {
                        $badge = "bg-blue";
                        $message = 'Aktif Trainee';
                    }
                } else {
                    $badge = "bg-orange";
                    $message = 'Belum pilih SBC';
                }
            }
            $status = "<span class='badge {$badge}'>{$message}</span>";
            $data[$key]['status'] = $status;

            $badgeSoal = 'bg-orange';
            $result_soal = '';
            if (!$each['has_soal_submitted']) {
                $badgeSoal = 'bg-white';
                $result_soal = 'Belum isi soal';
            } else {
                if ($each['has_soal_approved'] == 0) {
                    $badgeSoal = 'bg-orange';
                    $result_soal = 'Menunggu Hasil Nilai';
                } else {
                    if ($each['has_soal_approved'] == 1 || ($each['has_soal_approved'] == 2 && $each['response_recall'] == 1)) {
                        $badgeSoal = 'bg-green';
                        $result_soal = 'Berhasil';
                    } else {
                        if ($each['request_to_recall'] == 0) {
                            $badgeSoal = 'bg-red';
                            $result_soal = 'Failed & Waiting Recall';
                        } elseif ($each['request_to_recall'] == 1) {
                            $badgeSoal = 'bg-orange';
                            $result_soal = 'Waiting Approve Recall';
                        }
                    }
                }
            }
            $data[$key]['status_soal'] = "<span class='badge {$badgeSoal}'>{$result_soal}</span>";

            $badgeFinger = 'bg-orange';
            $resultFinger = '';
            if (!$each['tanggal_finger']) {
                $badgeFinger = 'bg-orange';
                $resultFinger = 'Belum Isi';
            } else {
                $badgeFinger = 'bg-green';
                $resultFinger = 'Sudah Isi';
            }
            $data[$key]['status_finger'] = "<span class='badge {$badgeFinger}'>{$resultFinger}</span>";

            $badgeDropMan = 'bg-orange';
            $resultDropMan = '';
            if (!$each['drop_manager']) {
                $badgeDropMan = 'bg-orange';
                $resultDropMan = 'Belum Drop';
            } else {
                $badgeDropMan = 'bg-green';
                $resultDropMan = 'Sudah Drop';
            }
            $data[$key]['drop_manager'] = "<span class='badge {$badgeDropMan}'>{$resultDropMan}</span>";


            

            $data[$key]['aksi'] = implode(' ', $aksi);
            // action button - end

            // remove account button - start
            $akun = [];
            if ($is_manager == false) {
                # code...
                if ($each['manager_id']) {
                    $akun[] = Html::a('Move SBC', null, [
                        'class'=>'btn btn-warning btn-xs btn-modal-reset-manager',
                        'data-id'=>$each['id'],
                    ]);
                }
                $akun[] = Html::button("Hapus Akun", [
                    'class'=>'btn btn-xs btn-danger btn-delete-account',
                    'data-id'=>$each['id'],
                ]);
            } else {
                $akun[] = 'not allowed';
            }
            $data[$key]['akun'] = implode(' ', $akun);
            // remove account button - end
        }

        return ['data'=>$data];
    }

    public function actionDownloadExcel()
    {
        if ($this->user->user_role_id != 4) return $this->redirect('/site/403');

        // $is_manager = Yii::$app->user->identity->user_role_id == 3 ? true : false;
        $model = Profil::find()
            ->joinWith(['lookupStatusProfil', 'user'])
            ->where(['user_role_id'=>5, 'm_profil.is_deleted'=>0])
            ->andWhere(['IS NOT', 'm_profil.tanggal_finger', null]);

        $model = $model->all();

        $no = 0;
        $data = [];
        foreach ($model as $key => $trainee) {

views/info-trainee/_mail_content_kamis.php
<?php
use yii\helpers\Html;
/* @var $this \yii\web\View view component instance */
/* @var $message \yii\mail\MessageInterface the message being composed */
/* @var $content string main view render result */
?>

<?php $this->beginPage() ?>
<?php $this->beginBody() ?>
<p>
    Friendly reminder ☺ <br><br>

    Selamat kepada kandidat yang diterima sebagai Management Trainee dan Business Consultant. <br>
    Untuk proses selanjutnya dan pelatihan trading, diharapkan kehadirannya pada : <br>
        Hari/tanggal  : <?= $date ?> <br>
        Waktu             : 13.00 - selesai <br>
        Tempat           : Wisma Bumiputra lantai 3 Jalan Asia Afrika no 141-149 Bandung <br>
        Pakaian           : Bebas, Rapi dan Sopan <br>
        <br>
        <br>
        Terimakasih, good luck! <br>
        Budi Suhud <br>
        PT Rifan Financindo Bandung <br>
</p>

<?php $this->endBody() ?>
<?php $this->endPage() ?>

views/info-trainee/_mail_content_rabu.php
<?php
use yii\helpers\Html;
/* @var $this \yii\web\View view component instance */
/* @var $message \yii\mail\MessageInterface the message being composed */
/* @var $content string main view render result */
?>

<?php $this->beginPage() ?>
<?php $this->beginBody() ?>
<p>
    Friendly reminder ☺ <br><br>

    Proses rekrutmen tahap selanjutnya yaitu Psikotest (tes tulis) yang akan dilaksanakan pada <br>
        Hari/tanggal  : <?= $date ?> <br>
        Waktu             : 13.00 - 16.00 <br>
        Tempat           : Wisma Bumiputra lantai 3 Jalan Asia Afrika no 141-149 Bandung <br>
<br>
        Membawa buku catatan dan alat tulis. Dan diharapkan untuk datang tepat waktu. <br>
        <br>
        <br>
        Terimakasih, good luck! <br>
        Budi Suhud <br>
        PT Rifan Financindo Bandung <br>
</p>

<?php $this->endBody() ?>
<?php $this->endPage() ?>

views/info-trainee/index.php
<?php
use yii\web\View; 
use yii\helpers\Html; 
$this->title = 'Informasi Trainee';
?>

<div class="box-header with-border">
    <h3 class="box-title"><?= isset($title) ? $title : $this->title; ?></h3>
</div>

<div class="box-body">
    <table id="table" class="table table-bordered table-striped table-responsive">
        <thead>
            <tr>
                <th class="fixed-column">Nama Lengkap</th>
                <th>Alamat</th>
                <th>Tempat, Tgl Lahir</th>
                <th>Umur</th>
                <th>No Handphone</th>
                <th>SBC</th>
                <th>Room</th>
                <th>Status Trainee</th>
                <th>Status Soal</th>
                <th>Form Finger</th>
                <th>Drop SBC</th>
                <!-- <th>Aksi</th> -->
                <?php if (Yii::$app->user->identity->user_role_id != 3): ?>
                    <th>Hapus Akun</th>
                <?php endif ?>
                <!-- <th>Hapus Akun</th> -->
            </tr>
        </thead>
    </table>

    <?php if (Yii::$app->user->identity->user_role_id == 4): ?>
        <?= Html::a('Download Excel Fingerprint', '/info-trainee/download-excel', ['class'=>'btn btn-warning']); ?>
        <?= Html::button('Generate Hasil Soal', ['class'=>'btn btn-info btn-generate-hasil-soal']); ?>
    <?php endif ?>
</div>

<input type='text' id='txt_user_role_id' value='<?php echo Yii::$app->user->identity->user_role_id ?>' style='display:none' readonly />

<div class="modal fade" id="modal-profile">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body" id="modal-profile-content">
                
            </div>
        </div>
    <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<?php
$this->registerJs($this->render('js/index.js'), View::POS_END);
?>

views/info-trainee/result_soal.php
<?php 

use yii\web\View; 
use yii\helpers\Html; 
?>
<style type="text/css">
    .dl-horizontal dt {
        text-align: left;
    }
</style>

<div class="box box-success">
    <div class="box-header">
        
    </div>
    <div class="box-body">
        <div class="col-md-6">
            <table class="table table-responsive">
                <tbody>
                    <?php foreach ($successList as $key => $each): ?>
                        <tr>
                            <td><?= $each; ?></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <table class="table table-responsive">
                <tbody>
                    <?php foreach ($failedList as $key => $each): ?>
                        <tr>
                            <td><?= $each; ?></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
</div>